version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: empik-core-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/empik
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    command: java -jar /app.jar
  db:
    image: postgres
    container_name: empik-db
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_DB: empik
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
